use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Coinfair Solana Backend API",
        description = "基于 Rust 和 Axum 的区块链推荐奖励系统 API 文档",
        version = "1.0.0",
        contact(
            name = "API Support",
            email = "support@coinfair.xyz"
        )
    ),
    paths(
        // System health check
        crate::api::health,
        // Authentication endpoints
        crate::api::auth_controller::generate_auth_message,
        crate::api::auth_controller::solana_login,
        crate::api::auth_controller::refresh_token,
        crate::api::auth_controller::get_user_profile,
        crate::api::auth_controller::logout,
        crate::api::auth_controller::check_auth_status,
        crate::api::auth_controller::list_authenticated_users,
        crate::api::auth_controller::get_user_permissions,
        crate::api::auth_controller::update_user_permissions,
        // Development Authentication endpoints
        crate::api::dev_auth_controller::generate_admin_token,
        crate::api::dev_auth_controller::generate_user_token,
        crate::api::dev_auth_controller::get_token_info,
        // Permission Management endpoints
        crate::api::permission_management_controller::get_global_config,
        crate::api::permission_management_controller::update_global_config,
        crate::api::permission_management_controller::toggle_global_read,
        crate::api::permission_management_controller::toggle_global_write,
        crate::api::permission_management_controller::emergency_shutdown,
        crate::api::permission_management_controller::toggle_maintenance_mode,
        crate::api::permission_management_controller::get_all_api_configs,
        crate::api::permission_management_controller::get_api_configs_stats,
        crate::api::permission_management_controller::test_permission,
        crate::api::permission_management_controller::reload_configuration,
        // Refer endpoints
        crate::api::refer_controller::get_upper,
        crate::api::refer_controller::get_uppers,
        crate::api::refer_controller::create_refers,
        // Reward endpoints
        crate::api::reward_controller::set_reward,
        crate::api::reward_controller::set_rewards,
        crate::api::reward_controller::get_reward,
        crate::api::reward_controller::get_rewards_by_day,
        crate::api::reward_controller::get_rewards_by_today,
        crate::api::reward_controller::get_all_rewards,
        crate::api::reward_controller::set_all_rewards,
        crate::api::reward_controller::get_rank_rewards,
        crate::api::reward_controller::list_rewards_by_address,
        crate::api::reward_controller::mock_rewards,
        // User endpoints
        crate::api::user_controller::user,
        crate::api::user_controller::mock_users,
        // Solana Swap endpoints
        crate::api::solana::swap_controller::swap_tokens,
        crate::api::solana::swap_controller::get_balance,
        crate::api::solana::swap_controller::get_price_quote,
        crate::api::solana::swap_controller::get_wallet_info,
        crate::api::solana::swap_controller::health_check,
        // Solana SwapV2 endpoints
        crate::api::solana::swap_v2_controller::compute_swap_v2_base_in,
        crate::api::solana::swap_v2_controller::compute_swap_v2_base_out,
        crate::api::solana::swap_v2_controller::transaction_swap_v2_base_in,
        crate::api::solana::swap_v2_controller::transaction_swap_v2_base_out,
        // Solana Position endpoints
        crate::api::solana::position_controller::open_position,
        crate::api::solana::position_controller::open_position_and_send_transaction,
        crate::api::solana::position_controller::calculate_liquidity,
        crate::api::solana::position_controller::get_user_positions,
        crate::api::solana::position_controller::get_position_info,
        crate::api::solana::position_controller::check_position_exists,
        crate::api::solana::position_controller::increase_liquidity,
        crate::api::solana::position_controller::increase_liquidity_and_send_transaction,
        crate::api::solana::position_controller::decrease_liquidity,
        crate::api::solana::position_controller::decrease_liquidity_and_send_transaction,
        // Solana CLMM Pool Creation endpoints
        crate::api::solana::clmm_pool_create::create_pool,
        crate::api::solana::clmm_pool_create::create_pool_and_send_transaction,
        // Solana CLMM Pool Query endpoints
        crate::api::solana::clmm_pool_query::get_pool_by_address,
        crate::api::solana::clmm_pool_query::get_pools_by_mint,
        crate::api::solana::clmm_pool_query::get_pools_by_creator,
        crate::api::solana::clmm_pool_query::query_pools,
        crate::api::solana::clmm_pool_query::get_pool_statistics,
        crate::api::solana::clmm_pool_query::get_pool_list,
        crate::api::solana::clmm_pool_query::get_pools_by_mint_pair,
        // Solana Classic AMM Pool endpoints
        crate::api::solana::cpmm_pool_create::create_classic_amm_pool,
        crate::api::solana::cpmm_pool_create::create_classic_amm_pool_and_send_transaction,
        // Solana Static Configuration endpoints
        crate::api::solana::static_config_controller::get_version,
        crate::api::solana::static_config_controller::get_auto_fee,
        crate::api::solana::static_config_controller::get_rpcs,
        crate::api::solana::static_config_controller::get_chain_time,
        crate::api::solana::static_config_controller::get_mint_list,
        crate::api::solana::static_config_controller::get_info,
        crate::api::solana::static_config_controller::get_clmm_config,
        // Token Management endpoints
        crate::api::solana::token_controller::push_token,
        crate::api::solana::token_controller::get_token_list,
        crate::api::solana::token_controller::query_tokens,
        crate::api::solana::token_controller::get_token_by_address,
        crate::api::solana::token_controller::search_tokens,
        crate::api::solana::token_controller::get_trending_tokens,
        crate::api::solana::token_controller::get_new_tokens,
        crate::api::solana::token_controller::get_token_stats,
        crate::api::solana::token_controller::update_token_status,
        crate::api::solana::token_controller::update_token_verification,
        crate::api::solana::token_controller::delete_token,
        // CLMM Configuration endpoints
        crate::api::solana::clmm_config_controller::get_clmm_configs,
        crate::api::solana::clmm_config_controller::save_clmm_config,
        // Solana NFT endpoints
        crate::api::solana::nft_controller::mint_nft,
        crate::api::solana::nft_controller::mint_nft_and_send_transaction,
        crate::api::solana::nft_controller::claim_nft,
        crate::api::solana::nft_controller::claim_nft_and_send_transaction,
        // Liquidity Line endpoints
        crate::api::solana::liquidity_line_controller::get_pool_liquidity_line,
        // Launch Event endpoints
        crate::api::solana::launch_event_controller::get_launch_event_by_signature,
        crate::api::solana::launch_event_controller::get_launch_event_stats,
        crate::api::solana::launch_event_controller::get_pending_migrations,
        crate::api::solana::launch_event_controller::get_failed_migrations_for_retry,
        // Static Price endpoint
        crate::api::static_controller::get_tokens_by_ids,
    ),
    components(
        schemas(
            // Database models
            database::refer::model::Refer,
            database::reward::model::Reward,
            database::reward::model::RewardItem,
            database::reward::model::RewardItemWithTime,
            database::user::model::User,
            // Token Management DTOs
            database::token_info::TokenPushRequest,
            database::token_info::TokenPushResponse,
            database::token_info::TokenListQuery,
            database::token_info::TokenListResponse,
            database::token_info::TokenInfo,
            database::token_info::TokenStatus,
            database::token_info::VerificationStatus,
            database::token_info::repository::TokenStats,
            crate::api::solana::token_controller::TokenSearchQuery,
            crate::api::solana::token_controller::TokenAddressPath,
            // Authentication models
            crate::auth::models::SolanaLoginRequest,
            crate::auth::models::AuthResponse,
            crate::auth::models::UserInfo,
            crate::auth::solana_auth::GenerateAuthMessageRequest,
            crate::auth::solana_auth::AuthMessageResponse,
            // Development Auth DTOs
            crate::api::dev_auth_controller::AdminTokenRequest,
            crate::api::dev_auth_controller::UserTokenRequest,
            crate::api::dev_auth_controller::DevTokenResponse,
            crate::api::dev_auth_controller::TokenInfoResponse,
            // CLMM Pool models
            database::clmm_pool::ClmmPool,
            database::clmm_pool::TokenInfo,
            database::clmm_pool::PriceInfo,
            database::clmm_pool::VaultInfo,
            database::clmm_pool::ExtensionInfo,
            database::clmm_pool::TransactionInfo,
            database::clmm_pool::SyncStatus,
            database::clmm_pool::PoolStatus,
            database::clmm_pool::TransactionStatus,
            database::clmm_pool::PoolStats,
            database::clmm_pool::PoolQueryParams,
            // DTOs
            crate::dtos::refer_dto::SetRefersDto,
            crate::dtos::reward_dto::SetRewardDto,
            crate::dtos::reward_dto::SetRewardsDto,
            crate::dtos::reward_dto::MockRewardsDto,
            crate::dtos::user_dto::SetUsersDto,
            // Solana DTOs
            crate::dtos::solana::swap::basic::SwapRequest,
            crate::dtos::solana::swap::basic::SwapResponse,
            crate::dtos::solana::swap::basic::BalanceResponse,
            crate::dtos::solana::swap::basic::PriceQuoteRequest,
            crate::dtos::solana::swap::basic::PriceQuoteResponse,
            crate::dtos::solana::common::WalletInfo,
            crate::dtos::solana::common::ErrorResponse,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::swap::basic::SwapResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::swap::basic::BalanceResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::swap::basic::PriceQuoteResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::common::WalletInfo>,
            crate::dtos::solana::common::ApiResponse<String>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::common::ErrorResponse>,
            crate::dtos::solana::common::TransactionStatus,
            // Solana SwapV2 DTOs
            crate::dtos::solana::swap::raydium::ComputeSwapV2Request,
            crate::dtos::solana::swap::raydium::SwapComputeData,
            crate::dtos::solana::swap::raydium::SwapComputeV2Data,
            crate::dtos::solana::common::TransferFeeInfo,
            crate::dtos::solana::common::RoutePlan,
            crate::dtos::solana::swap::raydium::TransactionSwapRequest,
            crate::dtos::solana::swap::raydium::TransactionSwapV2Request,
            crate::dtos::solana::common::TransactionData,
            crate::dtos::solana::swap::raydium::RaydiumResponse<crate::dtos::solana::swap::raydium::SwapComputeData>,
            crate::dtos::solana::swap::raydium::RaydiumResponse<crate::dtos::solana::swap::raydium::SwapComputeV2Data>,
            crate::dtos::solana::swap::raydium::RaydiumResponse<Vec<crate::dtos::solana::common::TransactionData>>,
            crate::dtos::solana::swap::raydium::RaydiumErrorResponse,
            // Solana OpenPosition DTOs
            crate::dtos::solana::position::open_position::OpenPositionRequest,
            crate::dtos::solana::position::open_position::OpenPositionResponse,
            crate::dtos::solana::position::open_position::CalculateLiquidityRequest,
            crate::dtos::solana::position::open_position::CalculateLiquidityResponse,
            crate::dtos::solana::position::open_position::GetUserPositionsRequest,
            crate::dtos::solana::position::open_position::UserPositionsResponse,
            crate::dtos::solana::position::open_position::PositionInfo,
            // Solana Pool Creation DTOs
            crate::dtos::solana::pool::creation::CreatePoolRequest,
            crate::dtos::solana::pool::creation::CreatePoolResponse,
            crate::dtos::solana::pool::creation::CreatePoolAndSendTransactionResponse,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::pool::creation::CreatePoolResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::pool::creation::CreatePoolAndSendTransactionResponse>,
            // CLMM Pool Query Response DTOs
            crate::dtos::solana::common::ApiResponse<Option<database::clmm_pool::ClmmPool>>,
            crate::dtos::solana::common::ApiResponse<Vec<database::clmm_pool::ClmmPool>>,
            crate::dtos::solana::common::ApiResponse<database::clmm_pool::PoolStats>,
            // Pool List DTOs
            database::clmm_pool::model::PoolListRequest,
            database::clmm_pool::model::PoolListResponse,
            database::clmm_pool::model::PaginationMeta,
            database::clmm_pool::model::FilterSummary,
            database::clmm_pool::model::TypeCount,
            database::clmm_pool::model::PoolType,
            crate::dtos::solana::common::ApiResponse<database::clmm_pool::model::PoolListResponse>,
            // Solana Classic AMM Pool DTOs
            crate::dtos::solana::pool::creation::CreateClassicAmmPoolRequest,
            crate::dtos::solana::pool::creation::CreateClassicAmmPoolResponse,
            crate::dtos::solana::pool::creation::CreateClassicAmmPoolAndSendTransactionResponse,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::pool::creation::CreateClassicAmmPoolResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::pool::creation::CreateClassicAmmPoolAndSendTransactionResponse>,
            // Solana Liquidity Management DTOs
            crate::dtos::solana::position::liquidity::IncreaseLiquidityRequest,
            crate::dtos::solana::position::liquidity::IncreaseLiquidityResponse,
            crate::dtos::solana::position::liquidity::IncreaseLiquidityAndSendTransactionResponse,
            crate::dtos::solana::position::liquidity::DecreaseLiquidityRequest,
            crate::dtos::solana::position::liquidity::DecreaseLiquidityResponse,
            crate::dtos::solana::position::liquidity::DecreaseLiquidityAndSendTransactionResponse,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::position::liquidity::IncreaseLiquidityResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::position::liquidity::IncreaseLiquidityAndSendTransactionResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::position::liquidity::DecreaseLiquidityResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::position::liquidity::DecreaseLiquidityAndSendTransactionResponse>,
            // Pool List DTOs
            crate::dtos::solana::pool::listing::NewPoolListResponse,
            crate::dtos::solana::pool::listing::PoolListData,
            crate::dtos::solana::pool::listing::PoolInfo,
            // Static DTOs
            crate::dtos::static_dto::VersionConfig,
            crate::dtos::static_dto::AutoFeeConfig,
            crate::dtos::static_dto::DefaultFeeConfig,
            crate::dtos::static_dto::RpcConfig,
            crate::dtos::static_dto::RpcNode,
            crate::dtos::static_dto::ChainTimeConfig,
            crate::dtos::static_dto::MintListResponse,
            crate::dtos::static_dto::TokenInfo,
            crate::dtos::static_dto::MintPriceResponse,
            crate::dtos::static_dto::PriceData,
            crate::dtos::static_dto::ApiResponse<crate::dtos::static_dto::VersionConfig>,
            crate::dtos::static_dto::ApiResponse<crate::dtos::static_dto::AutoFeeConfig>,
            crate::dtos::static_dto::ApiResponse<crate::dtos::static_dto::RpcConfig>,
            crate::dtos::static_dto::ApiResponse<crate::dtos::static_dto::ChainTimeConfig>,
            crate::dtos::static_dto::ApiResponse<crate::dtos::static_dto::MintListResponse>,
            crate::dtos::static_dto::ApiResponse<crate::dtos::static_dto::MintPriceResponse>,
            // CLMM Config DTOs
            crate::dtos::static_dto::ClmmConfig,
            crate::dtos::static_dto::SaveClmmConfigRequest,
            crate::dtos::static_dto::SaveClmmConfigResponse,
            // NFT DTOs
            crate::dtos::solana::nft::mint::MintNftRequest,
            crate::dtos::solana::nft::mint::MintNftResponse,
            crate::dtos::solana::nft::mint::MintNftAndSendTransactionResponse,
            crate::dtos::solana::nft::claim::ClaimNftRequest,
            crate::dtos::solana::nft::claim::ClaimNftResponse,
            crate::dtos::solana::nft::claim::ClaimNftAndSendTransactionResponse,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::nft::mint::MintNftResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::nft::mint::MintNftAndSendTransactionResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::nft::claim::ClaimNftResponse>,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::nft::claim::ClaimNftAndSendTransactionResponse>,
            // Liquidity Line DTOs
            crate::dtos::solana::pool::liquidity_line::PoolLiquidityLineRequest,
            crate::dtos::solana::pool::liquidity_line::PoolLiquidityLineData,
            crate::dtos::solana::pool::liquidity_line::LiquidityLinePoint,
            crate::dtos::solana::common::ApiResponse<crate::dtos::solana::pool::liquidity_line::PoolLiquidityLineData>,
            // Launch Event DTOs
            crate::dtos::solana::events::launch_event::LaunchEventResponse,
            crate::dtos::solana::events::launch_event::LaunchEventStatsResponse,
        )
    ),
    tags(
        (name = "系统状态", description = "系统健康检查和状态监控"),
        (name = "认证管理", description = "Solana钱包认证和用户管理"),
        (name = "开发认证", description = "开发环境下的令牌生成和管理"),
        (name = "权限管理", description = "API权限配置和管理"),
        (name = "refer", description = "推荐关系管理"),
        (name = "reward", description = "奖励系统"),
        (name = "user", description = "用户管理"),
        (name = "代币管理", description = "代币信息推送和管理接口"),
        (name = "代币查询", description = "代币信息查询和搜索接口"),
        (name = "代币统计", description = "代币统计信息查询接口"),
        (name = "管理员功能", description = "代币管理员功能，需要特殊权限"),
        (name = "Solana交换", description = "Solana 代币交换相关接口"),
        (name = "SwapV2兼容接口", description = "SwapV2 兼容接口，支持转账费"),
        (name = "Solana流动性", description = "Solana 流动性仓位管理接口"),
        (name = "Solana池子管理", description = "Solana CLMM池子创建接口"),
        (name = "CLMM池子查询", description = "CLMM池子查询和统计接口"),
        (name = "Solana经典AMM", description = "Solana 经典AMM池子创建接口"),
        (name = "系统配置", description = "系统配置相关接口"),
        (name = "代币信息", description = "代币信息相关接口"),
        (name = "CLMM配置管理", description = "CLMM配置管理相关接口"),
        (name = "Solana推荐NFT", description = "Solana推荐NFT相关接口"),
        (name = "流动性分布", description = "池子流动性分布查询接口"),
        (name = "LaunchEvent", description = "Launch事件查询和统计接口"),
        (name = "LaunchEvent统计", description = "Launch事件统计分析接口")
    )
)]
pub struct ApiDoc;
