# AWS ECS 部署已禁用 - 使用deploy.yml中的SSH部署方式
# 原因：MY_AWS_REGION等占位符变量导致凭证配置失败
# 解决方案：改用稳定的SSH直接部署到EC2服务器

name: Deploy to Amazon ECS (Disabled)

on:
  # 完全禁用自动触发，避免AWS凭证错误
  workflow_dispatch:
    inputs:
      notice:
        description: '⚠️ 此workflow已禁用，请使用deploy.yml进行SSH部署'
        required: true
        default: 'disabled'
        type: choice
        options:
          - disabled

env:
  # 标记为已禁用
  AWS_WORKFLOW_DISABLED: true

permissions:
  contents: read

jobs:
  disabled-notice:
    name: ⚠️ AWS ECS Workflow 已禁用
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
    - name: 📢 禁用通知
      run: |
        echo "⚠️ AWS ECS 部署workflow已被禁用"
        echo ""  
        echo "🔍 禁用原因:"
        echo "  - MY_AWS_REGION 等占位符变量导致凭证配置失败"
        echo "  - 需要复杂的AWS服务配置（ECR、ECS、Task Definition等）"
        echo ""
        echo "🚀 替代方案:"
        echo "  - 使用 deploy.yml 中的SSH直接部署方式"  
        echo "  - 更快、更稳定、更简单的部署流程"
        echo ""
        echo "📝 如需恢复AWS ECS部署:"
        echo "  1. 配置有效的AWS_REGION（如us-east-1）"
        echo "  2. 设置ECR_REPOSITORY、ECS_SERVICE等变量"
        echo "  3. 配置AWS_ACCESS_KEY_ID和AWS_SECRET_ACCESS_KEY"
        echo "  4. 创建ECS Task Definition文件"
        echo ""
        echo "✅ 当前部署状态: 使用deploy.yml的SSH方式正常工作"
